apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <html>
    <head><title>My Nginx Server</title></head>
    <body><h1>Welcome to my Nginx server!</h1></body>
    </html>
