version: "3.8"

services:
  fastapi:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "7007:8000"
    depends_on:
      - rabbitmq
      - worker
    env_file:
      - .env

  worker:
    build:
      context: ../../
      dockerfile: worker.Dockerfile
    depends_on:
      - rabbitmq
    env_file:
      - .env

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  streamlit:
    build:
      context: ../../
      dockerfile: streamlit.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
