name: ci

on:
  push:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'Dockerfile'
      - '.github/workflows/docker-ci.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository_owner }}/${{ github.event.repository.name }}:latest .
          docker push ${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
