name: ci

on:
  push:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'Dockerfile'
      - '.github/workflows/docker-ci.yml'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository_owner }}/${{ github.event.repository.name }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: latest
