name: Python CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config --local cache-dir ${{ github.workspace }}/.poetry/cache
          poetry install --with dev

      - name: Run Flake8
        run: poetry run flake8 .

      - name: Run Mypy
        run: poetry run mypy .

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config --local cache-dir ${{ github.workspace }}/.poetry/cache
          poetry install --with dev

      - name: Run pytest
        run: poetry run pytest .

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config --local cache-dir ${{ github.workspace }}/.poetry/cache
          poetry install --with dev

      - name: Build Python package
        run: |
          echo "Building Python package."
          poetry build

      - name: Publish package to GitHub Packages
        run: |
          echo "Publishing package to GitHub Packages."
          poetry config repositories.github "https://pypi.pkg.github.com/"
          poetry config http-basic."https://pypi.pkg.github.com/" "${{ github.actor }}" "${{ secrets.GITHUB_TOKEN }}"
          poetry publish --repository github --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ github.workspace }}/dist
